name: flutter_callkit_incoming_example
description: Demonstrates how to use the flutter_callkit_incoming plugin.

publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_callkit_incoming:
    path: ../

  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.0
  http: ^1.5.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/test.png
